config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/index.html.erb
<h1>My tasks</h1>
<% @tasks.each do |task| %>
  <div>
    <% if task.completed %>
      <input type="checkbox" name="<% task.title %>" checked>
    <% else %>
      <input type="checkbox" name="<%= task.title %>">
    <% end %>
    <label for="<%= task.title %>"><%= link_to task.title, task_path(task) %></label>
  </div>
<% end %>

<%= link_to 'Create task', new_task_path %>

app/views/tasks/index.html.erb
<h1>BEM-VINDO AO ÍNDICE DE TAREFAS!</h1>

<ul>
  <% @tasks.each do |task| %>
    <li><%= task.title %></li>
  <% end %>

</ul>